run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  lll:
    line-length: 120
  revive:
    rules:
      - name: comment-spacings
      - name: import-shadowing

issues:
  exclude-dirs:
    - third_party
    - builtin
    - examples
  exclude-rules:
    - path: api/
      linters:
        - lll
    - path: internal/
      linters:
        - dupl
        - lll