version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true
  skip-dirs:
    - third_party
    - builtin
    - examples

output:
  show-stats: true
  sort-order:
    - file
    - linter

linters:
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters.lll:
  line-length: 120

linters.revive:
  rules:
    - name: comment-spacings
    - name: import-shadowing

issues:
  exclude-files:
    - "api/.*"
    - "internal/.*"